version: '3.5'
services:
  flask:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PORT=4000
      - DB=mongo://mongodb:27017/dev
  react:
    build:
      context: ./modules/client
      dockerfile: Dockerfile
    volumes:
      - './modules/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000